version: '3.1'

services:
  spring:
    image: hyness/spring-cloud-config-server:latest
    restart: always
    ports:
      - 8888:8888
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/devova/vault-docker-compose
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS=config/{application}/,config/
#    volumes:
#      - ./deployment/spring.config.yml:/config/application.yml