spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/devova/vault-docker-compose
            search-paths: 'config/{application}'
            cloneOnStart: true
---
def-key: 1