spring:
    cloud:
      config:
        overrideNone: true
        server:
          git:
            uri: https://github.com/devova/vault-docker-compose
            search-paths: 'config/{application}'
            cloneOnStart: true

defkey: 1